import 'package:flutter_ui/features/transactions/domain/transaction.dart';

final kTestTransactions = [
  Transaction(
    id: '1',
    amount: 19000,
    transactionAt: DateTime.now(),
    note: 'Deposited to NBL',
    categoryId: '11',
    walletId: '3',
    transactionType: TransactionType.income,
  ),
  Transaction(
    id: '2',
    amount: 62526.86,
    transactionAt: DateTime.now(),
    note: 'Deposited to BOK',
    categoryId: '11',
    walletId: '4',
    transactionType: TransactionType.income,
  ),
  Transaction(
    id: '3',
    amount: 522515.31,
    transactionAt: DateTime.now(),
    note: 'Deposited to EBL',
    categoryId: '11',
    walletId: '2',
    transactionType: TransactionType.income,
  ),
  Transaction(
    id: '4',
    amount: 7364.45,
    transactionAt: DateTime.now(),
    note: 'Buy grocery from Bhatbhateni',
    categoryId: '6',
    walletId: '2',
  ),
  Transaction(
    id: '5',
    amount: 30000,
    transactionAt: DateTime.now(),
    note: 'Teej festival shopping for Mom, Vauju and Budi',
    categoryId: '4',
    walletId: '4',
  ),
  Transaction(
    id: '6',
    amount: 5000,
    transactionAt: DateTime.now(),
    note: 'Transferred to Dai for Medical Expenses',
    categoryId: '8',
    walletId: '2',
  ),
  Transaction(
    id: '7',
    amount: 10000,
    transactionAt: DateTime.now(),
    note: 'Travel Expense for Sasurali',
    categoryId: '12',
    walletId: '2',
  ),
  Transaction(
    id: '8',
    amount: 10000,
    transactionAt: DateTime.now(),
    note: 'Money for Samuha',
    categoryId: '10',
    walletId: '7',
  ),
  Transaction(
    id: '9',
    amount: 10000,
    transactionAt: DateTime.now(),
    note: 'Money for Samuha',
    categoryId: '10',
    walletId: '2',
  ),
  Transaction(
    id: '10',
    amount: 19000,
    transactionAt: DateTime.now(),
    note: 'Mobile Recharge 4878',
    categoryId: '12',
    walletId: '5',
  ),
  Transaction(
    id: '11',
    amount: 3310,
    transactionAt: DateTime.now(),
    note: 'Scooty Repair and Maintenance',
    categoryId: '13',
    walletId: '1',
  ),
];
